### ISSUE TITLE
Crash after leaving room

### ISSUE THREAD

**Issue by Curtisww17** [Curtisww17/VoteNote-iOS#6]
What i did: created a room, looked at the room and queue pages a few times, closed the room, then navigated to the host page to make a new room.
Error: Thread 1: "*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray"

**Comment by Curtisww17** [comment]
figured out this bug is located in the getRoom() method in dbConnection.swift on the line "let rm = query?.documents[0].data()"

**Comment by acramernc** [comment]
I have no clue why this function is getting called, currently the only functions that call getRoom are getUsers and getUser (i think because of the anonymizing stuff @Curtisww17 wrote) but those functions aren't being called outside of the room either except for potentially in the case of initializeAnon(). Whoever wrote initializeAnon needs to make sure it isn't called outside a room or we need to redo how anonymizing works

**Comment by acramernc** [comment]
Added a bunch of things in #10 which should resolve this issue
